#ifndef __CONFIG_H__
#define __CONFIG_H__

#define CONFIG_SCREEN_WIDTH  480
#define CONFIG_SCREEN_HEIGHT 320
#define CONFIG_SCREEN_LINES  16
#define CONFIG_SCREEN_LINE_HEIGHT (CONFIG_SCREEN_HEIGHT/CONFIG_SCREEN_LINES)

#endif // __CONFIG_H__