#ifndef __SRC_CONFIG_H__
#define __SRC_CONFIG_H__

#define FS_PREFIX "/sdcard"
#define CONFIG_SCREEN_WIDTH  480
#define CONFIG_SCREEN_HEIGHT 320
#define CONFIG_SCREEN_LINES 8
#define CONFIG_SCREEN_LINE_HEIGHT (CONFIG_SCREEN_HEIGHT/CONFIG_SCREEN_LINES)

#define PIN_NUM_MOSI 23
#define PIN_NUM_MISO 19
#define PIN_NUM_CLK  18
#define PIN_NUM_CS    5

// ESP32
#define CONFIG_IP_REMOTE_SIM    "192.168.254.181:11111"
// LAPTOP
// #define CONFIG_IP_REMOTE_SIM    "192.168.254.125:11111"

#endif // __SRC_CONFIG_H__
